---
driver:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: busser

platforms:
- name: centos-7
  driver_config:
    image: centos:7
    platform: centos

suites:
  - name: default
    run_list:
    - recipe[hello_dokken::default]

